### ISSUE TITLE
在有雙字幕的狀況下進入全螢幕字體大小會變得很小

### ISSUE THREAD

**Issue by aweimeow** [dannvix/NflxMultiSubs#1]
原諒我用中文來開 issue :P 

如果現在 Chrome 處於未全螢幕的狀態，並且有雙字幕載入時，
若此時雙擊 NetFlix 視窗使其放大成全螢幕，會發現第二字幕如下圖：

<img width="1280" alt="2018-03-08 12 57 06" src="https://user-images.githubusercontent.com/5120010/37106398-af931a70-226c-11e8-8969-4c22c1080da2.png">

那一小陀擠在一起像小螞蟻的東西就是第二字幕，而且主字幕也會飄到畫面中間。

<hr>

目前發現如果先進入全螢幕（Cmd + Shift + F in Mac）再點擊影片播放，則不會有這個問題：

<img width="1280" alt="2018-03-08 1 01 01" src="https://user-images.githubusercontent.com/5120010/37106469-e14831ea-226c-11e8-833b-902c41a02e0e.png">

**Comment by dannvix** [comment]
Hi @aweimeow

感謝回報！但在我的環境似乎無法重現這個問題…
偶爾在「全螢幕切換」與「下方控制列顯示／隱藏」的過程中會有錯位發生，但過一下（或是下一條字幕）應該就會回到正常顯示。

請問更新到最新版本 (`v1.4.3`) 還有這個現象嗎？謝謝

**Comment by dannvix** [comment]
Hi @aweimeow 

後來也有其他使用者回報相同的問題，初步研判是字形大小計算錯誤，預計於新版本修正，謝謝

**Comment by dannvix** [comment]
我們發佈了新版本 `v1.5.0` 來試著解決這個問題，請有遇到的朋友再試試看，謝謝！

**Comment by hearsilent** [comment]
LGTM

**Comment by aweimeow** [comment]
@dannvix 更新的版本解決問題了 🎉
