### ISSUE TITLE
TODO: 將文件都變成中英雙語

### ISSUE THREAD

**Issue by hiiwave** [dannvix/NflxMultiSubs#11]
> Miscellaneous
> -------------
> - [ ] 將文件都變成中英雙語？

我很樂意貢獻這部分（這也是列在那裏最容易的事了 XD）
這裡的文件是指 `README.md` 及 `TODO.md` 對吧?
Let me know if you're glad with this or you prefer doing it on you own 😄

**Comment by dannvix** [comment]
Hello @hiiwave 

沒錯！目前以 `README.md` 和 `TODO.md` 為主。

很高興您願意幫忙這個部分！因為我英文不好，寫起來就是卡卡的……。至於中、英文要放在同一個檔案，或是分不同檔案？不清楚何種方式比較適合閱讀，因此尚未定案。

**Comment by hiiwave** [comment]
我在想的是 `README.md` 的 header (段落*特色*前) 加一行：

For English Translation, please refer to [here](README_en.md).

here 指到 `README_en.md`。

感覺加入英文的主要目的是讓整個專案更容易被internation users 使用及參與，這些客群大概不太懂中文，
所以我感覺比起像雙語字幕中英文夾雜，分開似乎是比較有道理的。你覺得呢？

**Comment by hiiwave** [comment]
先翻了一下(#12)，看這樣的呈現方式是否滿意？也幫忙review一下哦～

**Comment by dannvix** [comment]
Merged #12 :clap: :clap: :clap:

**Comment by dannvix** [comment]
Hello @hiiwave 

基於您的協助，我在 commits b3a1a8c 與 b6dbaf6 裡按照自己的意思調整了一些內容，希望您別見怪 😃

**Comment by hiiwave** [comment]
當然～不客氣 😉
