### ISSUE TITLE
無法點選

### ISSUE THREAD

**Issue by yeanla** [dannvix/NflxMultiSubs#19]
網頁版netflix更新後 
看影片時無法使用滑鼠調整全螢幕、音量、時間軸等內容
只能使用快捷鍵調整

content.min.js:1 NflxMultiSubs> Intercepted: https://assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0009.566.011.js
content.min.js:1 NflxMultiSubs> FYI: "net::ERR_BLOCKED_BY_CLIENT" error is intented (for player code patching)
assets.nflxext.com/en_us/ffe/player/html/cadmium-playercore-6.0009.566.011.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
blob:https://www.netflix.com/14e5caa9-cbc6-4992-a40d-1d7336b84a99:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
content.min.js:1 NflxMultiSubs> Patched: callback
content.min.js:1 NflxMultiSubs> Patched: hi-res hack
content.min.js:1 NflxMultiSubs> Injected: nflxmultisubs.min.js
nflxmultisubs.min.js:8 NflxMultiSubs> Resize: 811x635 (80561.9999999999)
nflxmultisubs.min.js:8 NflxMultiSubs> Linked: pjhnilfooknlkdonmjnleaomamfehkli
nflxmultisubs.min.js:8 NflxMultiSubs> Player: loaded=6.0009.566.011
nflxmultisubs.min.js:8 NflxMultiSubs> Manifest: 80065731
nflxmultisubs.min.js:8 NflxMultiSubs> Subtitle "en" auto-enabled to match audio
nflxmultisubs.min.js:8 NflxMultiSubs> Subtitle "英文 [CC]" downloading
nflxmultisubs.min.js:8 NflxMultiSubs> Subtitle "英文 [CC]" loaded
nflxmultisubs.min.js:8 NflxMultiSubs> Started: renderer loop
nflxmultisubs.min.js:8 NflxMultiSubs> Resize: 1366x635 (108269.49999999988)
nflxmultisubs.min.js:8 NflxMultiSubs> Resize: 811x635 (258521.09999999992)

**Comment by wabilin** [comment]
我好像無法重現這個問題 FireFox & Chrome 目前都正常使用

**Comment by meimei081** [comment]
我也是播放器更新成如下所示後，就無法正常使用：
![screen](https://user-images.githubusercontent.com/40551461/41825803-d53428c4-7856-11e8-8e26-b10e63266a47.png)

**Comment by dannvix** [comment]
感謝善心人士 @Wen-Liu 提供了新版播放器 (代號為 `Neo`) 的 DOM 結構，我們得以推出新版 (`v1.6.5) 來解決相容性問題！

並且很開心地發現「第二字幕選單」在新版播放器還能正常運作 :muscle: :muscle: :muscle:
![photo_2018-07-15_22-42-46](https://user-images.githubusercontent.com/80781/42735213-baac0e54-8882-11e8-8f66-8effa20b79b3.jpg)

**Comment by zackexplosion** [comment]
@dannvix 請問新版本發佈了嗎？剛剛發現加這個也可以解決，讓點擊可以穿透就行了。

nflxmultisubs.js

```
-  wrapper.style = 'position:absolute; top:0; left:0; width:100%; height:100%; z-index:2; display:flex; align-items:center;';
+  wrapper.style = 'position:absolute; top:0; left:0; width:100%; height:100%; z-index:2; display:flex; align-items:center; pointer-events:none;';
```

**Comment by dannvix** [comment]
Hello @zackexplosion 

新版本 `v1.6.5` 已於昨日發佈至 [Chrome Web Store](https://chrome.google.com/webstore/detail/nflxmultisubs-netflix-mul/pjhnilfooknlkdonmjnleaomamfehkli) 與 [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/nflxmultisubs/)。謝謝您關於 `pointer-events: none` 的建議，之後的版本可以加入。
