### ISSUE TITLE
Error: cannot inject hi-res hack

### ISSUE THREAD

**Issue by M157q** [dannvix/NflxMultiSubs#2]
先感謝寫出了一個這麼棒的套件 XD
遇到沒辦法強制 1080p 的 error
想說會不會是裝了其他 plugin 的問題
所以開了個新的 profile 只有裝這個 extension
但還是一樣遇到了想說回報一下

遇到這個 error 沒有強制 1080p
但搭配 Netflix 1080p 這個套件是可以使用的

以下是錯誤訊息
---

瀏覽器版本：Chromium Version 65.0.3325.146 (Developer Build) (64-bit)

錯誤訊息：
```
chrome.webRequest.onBeforeRequest.addListener((a)=>(console.log(`Denying: ${a.url}`),{cancel:!0}),{urls:['https://assets.nflxext.com/*cadmium-playercore*'],types:['script']},['blocking']);
```
```
window.addEventListener('load',()=>{['jszip.min.js','injected.min.js'].forEach((a)=>{let b=document.createElement('script');b.setAttribute('type','text/javascript'),b.setAttribute('src',chrome.extension.getURL(a)),document.head.appendChild(b),console.log(`Injected: ${a}`)})});const patchNflxPlayerCore=(a)=>{let b=a.indexOf('a.textTracks.forEach');if(0<=b){const c=`(window.__NflxMultiSubs&&window.__NflxMultiSubs.updateManifest(a));`;a=a.substr(0,b)+c+a.substr(b),console.log('Patched: callback')}else console.error('Error: cannot inject callback');return b=a.indexOf('a&&this.wo.push('),0<=b?(a=a.substr(0,b)+a.substr(b+3),console.log('Patched: hi-res hack')):console.error('Error: cannot inject hi-res hack'),a},observer=new MutationObserver((a)=>{a.forEach((a)=>{a.addedNodes.forEach((a)=>{if('script'!==a.nodeName.toLowerCase())return;if('player-core-js'!==a.id)return;const b=a,c=b.getAttribute('src');b.removeAttribute('src'),console.log(`Intercepted: ${c}`),fetch(c).then((a)=>a.text()).then((c)=>{c=patchNflxPlayerCore(c);const d=new Blob([c],{type:'text/javascript'});b.setAttribute('src',URL.createObjectURL(d)),b.addEventListener('load',()=>{URL.revokeObjectURL(a.getAttribute('src'))})}),observer.disconnect()})})}),options={subtree:!0,childList:!0};observer.observe(document,options);
```

截圖：

![20180309_11 10 10](https://user-images.githubusercontent.com/1645228/37188504-7ab5183e-238a-11e8-9d75-3efba4bb4d11.jpg)

![20180309_11 06 34](https://user-images.githubusercontent.com/1645228/37188443-2115a640-238a-11e8-9be5-cc32ee960649.jpg)

**Comment by dannvix** [comment]
Hi @M157q 

感謝回報與在 Twitter 上分享！
由於您提供了詳細的 log，所以我們能很快地找到問題：Netflix 的新版播放器做了一些更動，導致啟用 1080p 失敗，這個問題已經在最新版 [`v1.4.5`](https://github.com/dannvix/NflxMultiSubs/releases/tag/lite-1.4.5) 修正，請再試試看！

----

另外說明一下為什麼 README 裡指出可能與其他套件衝突的原因。

如您安裝之 [netflix-1080p](https://github.com/truedread/netflix-1080p)，其底層做法為 **該套件附帶有一份「修改過後的 Netflix 播放器核心」** ，在您開啟 Netflix 時攔截瀏覽器發出的請求，並置換為套件附帶的修改版。

此種做法在短期內保證 1080p 能被啟用，但若此類套件更新不夠即時，會 **導致使用者載入舊版 Netflix 播放器** （也就是該套件內附帶的那份，事實上它現在就是舊的）。並且本套件可能與之相衝，我們不會跟著它們的修改版跑。

本套件在底層為即時解析 Netflix 播放器核心程式碼，並動態修改程式碼來整合本套件與播放器。此種做法能 **保證使用者永遠都是載入「最新的官方版播放器」**。但技術門檻較高，也有可能因為程式碼更動而失效……。

----

順帶一提，本套件在 `v1.4.5` 版改進了與其他套件的相容性（想辦法繞過他們 XD），並且在 JavaScript console 裡增加更多 log，如下圖示例：第一次載入的播放器遭 `netflix-1080p` 替換為舊版，隨後本套件嘗試繞過並獲得最新的播放器核心。

![NflxMultiSubs v1.4.5 fetches the latest player core](https://user-images.githubusercontent.com/80781/37215824-00e59c26-23f4-11e8-99a0-caab4825d031.png)

**Comment by dannvix** [comment]
方才發佈 `v.1.4.9` 改用更精確的方法 (AST) 來解析 Netflix 播放器核心，應該「啟用 1080p」的功能比較可靠了（這明明是順便做的說…… XD）。所以這個 issue 要關掉囉～

**Comment by M157q** [comment]
@dannvix 感謝
我安裝 Chrome Web Store 的 1.4.9 版本已經可以看到 1080p 畫質

我覺得這個 repo 丟到 Hacker News 和 Reddit 上有爆紅的潛力
可以試試看 XD

**Comment by waynelai614** [comment]
剛好有在Netflix上需要雙語字幕的需求進而找到此套件
基於好奇如何實作研究了一下 source code, 沒想到還有在 Netflix 的 js 內 inject 自己 extension function callback 的方法

感謝寫出了一個這麼棒的套件 🎉🎉🎉

若可以將開發過程以及如何實作
寫成一篇技術文章分享給大家那就更好了 :)

**Comment by dannvix** [comment]
Hi @waynelai614 

很高興你喜歡這個專案，謝謝！
技術文章的部分有緣的話再寫來分享吧 XD

**Comment by hiiwave** [comment]
棒插件與期待技術文章 +1 😄
