### ISSUE TITLE
字幕重叠

### ISSUE THREAD

**Issue by ifduyue** [dannvix/NflxMultiSubs#21]
![image](https://user-images.githubusercontent.com/568900/43152468-33ce0a74-8fa1-11e8-80e7-2a1693e520f2.png)

句子太长字体太大限定宽度导致重叠到一起了？

**Comment by wabilin** [comment]
這是否和 #16 是同一個問題?

**Comment by ifduyue** [comment]
@wabilin 谢谢，是同一个问题
