### ISSUE TITLE
字幕重叠现象

### ISSUE THREAD

**Issue by paullkim** [dannvix/NflxMultiSubs#22]
你好

观看‘老友记’的时候发现长一点的第一字幕会重叠
望改进，谢谢！

![screen shot 2018-09-13 at 08 25 33](https://user-images.githubusercontent.com/28541013/45460340-57d93a00-b72f-11e8-9ae5-384c2e57b826.png)

**Comment by hiiwave** [comment]
Duplicate of #16.
