### ISSUE TITLE
how to unleash 1080p.....?

### ISSUE THREAD

**Issue by hobrother1** [dannvix/NflxMultiSubs#25]
I can't unleash 1080p with chrome browser

I can unleash with Netflix-1080p extension

But NflxMultisubs is not work with Netflix-1080p

how can I unleash 1080p with Nflxmultisubs?

**Comment by wabilin** [comment]
Duplicate with #15

Sorry for #15 was written in Chinese.
In short, NflxMultiSubs have some problem with unleashing 1080p in Chrome now.
