### ISSUE TITLE
1080p功能用不了了

### ISSUE THREAD

**Issue by SoVieTing** [dannvix/NflxMultiSubs#37]
现在只能到720p了，麻烦作者修复下。和另一个强制1080的扩展冲突属实遗憾。

**Comment by dannvix** [comment]
The latest version (`v1.7.1`, published by @hobodrifterdavid) can work with [netflix-1080p](https://chrome.google.com/webstore/detail/netflix-1080p/cankofcoohmbhfpcemhmaaeennfbnmgp). Try it.
