### ISSUE TITLE
第二字幕錯誤

### ISSUE THREAD

**Issue by FlandreDaisuki** [dannvix/NflxMultiSubs#5]
看 console 好像是抓到下一集的manifest了 😂
- - -
畫面：
![_001](https://user-images.githubusercontent.com/5981459/37566200-eaa77a34-2af0-11e8-905d-df4c662fc0ae.png)

console:
![_002](https://user-images.githubusercontent.com/5981459/37566206-00239dca-2af1-11e8-9f3a-b6e7f4ea2ae9.png)

**Comment by dannvix** [comment]
Hi @FlandreDaisuki 

我們已於最新版 `v1.6.3` 修正這個問題，感謝您的回報！ 👍

**Comment by FlandreDaisuki** [comment]
@dannvix 還是出現第二字幕錯集的情況
這次發生在看完結束 Netflix 自動跳下一集的時候
載入的第二字幕是還是上一集的

console:
```
// 看 80097903 時清掉所有 console ，自動跳下一集時只有這些 logs
// 此時的第二字幕還是 80097903 的
NflxMultiSubs> Player: loaded=5.0008.803.051
nflxmultisubs.min.js:8:32812
NflxMultiSubs> Manifest: 80097904
nflxmultisubs.min.js:8:32812
NflxMultiSubs> Ignored: manifest 80097904 not playing
```

另外 `this.videoElem is null` 的 error 還是在，不知道有沒有相關

**Comment by dannvix** [comment]
Hello @FlandreDaisuki 

感謝大大貢獻 PR！已 merged <(__  __)>

由於我這裡無法重現問題，所以也無法立即確認是否解決；讓我們測試個幾天，如果沒再發生，我再更新版號並發佈至 Chrome Web Store 和 Firefox Add-ons；暫時先 reopen 這個 issue 哦！

**Comment by FlandreDaisuki** [comment]
可惡 QQ
「狂賭之淵」可以正常 work 但「惡魔人」無法

在結尾跳下一集時
前者會 terminate render loop 但後者不會，所以 ignore manifest 就再起不能。
還要想一下這兩個要怎麼同時都能跑...

**Comment by dannvix** [comment]
Hello @FlandreDaisuki 

感謝！ #10 已 merged

一樣讓我們再觀察個幾天～若問題不再出現，並且沒有副作用，那我會發佈新版來改善這個問題！

**Comment by dannvix** [comment]
新版本 `v1.6.4` 已發佈至 [Chrome Web Store](https://chrome.google.com/webstore/detail/nflxmultisubs-netflix-mul/pjhnilfooknlkdonmjnleaomamfehkli) 與 [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/nflxmultisubs/) 👍
