### ISSUE TITLE
未能自動切換1080p

### ISSUE THREAD

**Issue by unkokao** [dannvix/NflxMultiSubs#6]
![default](https://user-images.githubusercontent.com/37588567/37664867-030132c6-2c97-11e8-9e37-c5dc76a77af8.png)
![123](https://user-images.githubusercontent.com/37588567/37664924-1e136e80-2c97-11e8-966a-b0741a8a4a3a.png)

**Comment by dannvix** [comment]
Hello @unkokao 

感謝提供資訊。按照您的擷圖，本套件有成功啟用 1080p 高畫質播放（見 `Patched: hi-res hack` 行）；我們使用相同版本的 Chrome （見 `(2)` ）實際測試您所觀看的影片（“Marvel's Jessica Jones” S2:E13，見 `(1)` ），亦有成功切換至 1080p 畫質（見 `(3)` ）。

本套件是讓 Netflix 在 Chrome 也可以切換至 1080p（原本只能到 720p），**並非強制切換畫質喔**，實際播放時 Netflix 仍會依照各項因素（如電腦環境、網路速度……）來自動切換。

![Netflix-80130326-1080p](https://user-images.githubusercontent.com/80781/37712158-fd404dd8-2d4d-11e8-806c-1a7ea3f6b3cb.jpg)
